version: "3"

services: 
  firebase: 
    image: "cg.shop-backend"
    build: 
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"  
      - "5001:5001"  
      - "9005:9005"  
    volumes: 
      - .:/app